allowBuilds:
  "@parcel/watcher": true
  "@playwright/browser-chromium": true
  "@swc/core": true
  better-sqlite3: true
  esbuild: true
  msw: true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@4.0.62'
  - '@ai-sdk/gateway@4.0.91'
  - '@ai-sdk/mcp@2.0.57'
  - '@ai-sdk/provider-utils@5.0.47'
  - '@ai-sdk/react@4.0.116'
  - ai@7.0.113
  - framer-motion@13.4.3
  - icu-minify@4.14.7
  - libphonenumber-js@1.13.14
  - lucide-react@1.48.0
  - next-intl-swc-plugin-extractor@4.14.7
  - next-intl@4.14.7
  - use-intl@4.14.7
overrides:
  livekit-client: 2.16.1
